import "server-only";

import { existsSync, readFileSync, appendFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";

/**
 * Dev-mode auto-generation of CINATRA_ENCRYPTION_KEY.
 *
 * Behavior:
 * - Skips entirely when NODE_ENV === "production".
 * - Skips when the env var is already populated (>=32 chars).
 * - Generates `crypto.randomBytes(32).toString("hex")` (64 hex chars = 32 bytes).
 * - Persists `CINATRA_ENCRYPTION_KEY=<value>` to <repo-root>/.env.local
 *   (idempotent: returns early if the file already contains a non-empty
 *   `CINATRA_ENCRYPTION_KEY=` line).
 * - Sets `process.env.CINATRA_ENCRYPTION_KEY` so the current process can use
 *   the key without restart.
 * - Logs once on generation; logs once and noops on already-set.
 *
 * Never throws. Any I/O error (no .env.local, read-only FS, race) is logged
 * with `console.warn` and swallowed so server boot is never blocked.
 */
export function ensureDevEncryptionKey(): void {
  if (process.env.NODE_ENV === "production") return;

  const existing = process.env.CINATRA_ENCRYPTION_KEY?.trim() ?? "";
  if (existing.length >= 32) return;

  const envPath = resolve(process.cwd(), ".env.local");

  // Re-check the file — env may have been populated by another process or a
  // prior run that wrote to .env.local without us reloading it.
  try {
    if (existsSync(envPath)) {
      const contents = readFileSync(envPath, "utf8");
      const match = contents.match(/^CINATRA_ENCRYPTION_KEY=(.+)$/m);
      if (match && match[1] && match[1].trim().length >= 32) {
        // .env.local already has it — propagate to process.env.
        process.env.CINATRA_ENCRYPTION_KEY = match[1].trim();
        console.log(
          "[dev-encryption-key] CINATRA_ENCRYPTION_KEY found in .env.local — propagated to process.env.",
        );
        return;
      }
    }
  } catch (err) {
    console.warn(
      "[dev-encryption-key] could not read .env.local; proceeding to generate:",
      err instanceof Error ? err.message : err,
    );
  }

  const key = randomBytes(32).toString("hex");

  // Append (not overwrite) so we never clobber unrelated values.
  // Prefix with a header comment for ops legibility.
  const block = `\n# Auto-generated by dev-encryption-key-bootstrap at ${new Date().toISOString()}\nCINATRA_ENCRYPTION_KEY=${key}\n`;
  try {
    appendFileSync(envPath, block, { mode: 0o600 });
    process.env.CINATRA_ENCRYPTION_KEY = key;
    console.log(
      `[dev-encryption-key] generated CINATRA_ENCRYPTION_KEY and appended to ${envPath}.`,
    );
  } catch (err) {
    // Read-only FS, permission error, or worktree without .env.local — fall
    // back to in-memory only. The wizard will continue showing /setup/key
    // (because the file isn't persistent) but the current process can use
    // the key for the lifetime of this server.
    process.env.CINATRA_ENCRYPTION_KEY = key;
    console.warn(
      `[dev-encryption-key] could not persist key to ${envPath}; using in-memory key for this process only:`,
      err instanceof Error ? err.message : err,
    );
  }
}
