import "server-only";
import { randomUUID, timingSafeEqual } from "node:crypto";

import {
  readConnectorConfigFromDatabase,
  writeConnectorConfigToDatabase,
} from "@/lib/database";
import { getDrupalAPISettings } from "@/lib/drupal-api";

const WIDGET_AUTH_CONFIG_KEY = "drupal_widget_auth";

export type DrupalWidgetAuthConfig = {
  apiKey: string;
  generatedAt: string;
};

export function readDrupalWidgetAuthConfig(): DrupalWidgetAuthConfig | null {
  return readConnectorConfigFromDatabase<DrupalWidgetAuthConfig | null>(
    WIDGET_AUTH_CONFIG_KEY,
    null,
  );
}

export function generateDrupalWidgetAuthConfig(): DrupalWidgetAuthConfig {
  const config: DrupalWidgetAuthConfig = {
    apiKey: `${randomUUID()}-${randomUUID()}`,
    generatedAt: new Date().toISOString(),
  };
  writeConnectorConfigToDatabase(WIDGET_AUTH_CONFIG_KEY, config);
  return config;
}

/**
 * CORS origin allowlist for the Drupal widget.
 * Reflects the exact Origin header value when it matches a configured Drupal instance siteUrl
 * (case-insensitive, trailing slashes ignored). Returns null otherwise.
 */
export function resolveDrupalWidgetOrigin(originHeader: string | null): string | null {
  if (!originHeader) return null;
  const settings = getDrupalAPISettings();
  const normalize = (v: string) => v.replace(/\/+$/, "").toLowerCase();
  const want = normalize(originHeader);
  for (const instance of settings.instances) {
    if (normalize(instance.siteUrl) === want) return originHeader;
  }
  return null;
}

/**
 * Bearer token validator for the Drupal widget. Compares against the apiKey stored
 * in connector_config (UUID-pair generated by generateDrupalWidgetAuthConfig).
 */
export function validateDrupalWidgetToken(token: string): boolean {
  if (!token) return false;
  const config = readDrupalWidgetAuthConfig();
  if (!config?.apiKey) return false;
  const a = Buffer.from(token);
  const b = Buffer.from(config.apiKey);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/**
 * CORS headers reflecting the validated origin. Use only after resolveDrupalWidgetOrigin
 * returns non-null. Never use a wildcard origin; responses must be scoped to a configured
 * Drupal site origin.
 */
export function buildDrupalCorsHeaders(allowedOrigin: string): Record<string, string> {
  return {
    "Access-Control-Allow-Origin": allowedOrigin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Credentials": "false",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}
