import "server-only";
import { Buffer } from "node:buffer";
import { createHmac, randomBytes, randomUUID, timingSafeEqual } from "crypto";
import {
  readConnectorConfigFromDatabase,
  writeConnectorConfigToDatabase,
} from "@/lib/database";
import { getWordPressAPISettings } from "@/lib/wordpress-api";

const WIDGET_AUTH_CONFIG_KEY = "wordpress_widget_auth";

export type WidgetAuthConfig = {
  apiKey: string;
  webhookSecret: string;
  generatedAt: string;
};

export function readWidgetAuthConfig(): WidgetAuthConfig | null {
  return readConnectorConfigFromDatabase<WidgetAuthConfig | null>(
    WIDGET_AUTH_CONFIG_KEY,
    null,
  );
}

export function generateWidgetAuthConfig(): WidgetAuthConfig {
  const config: WidgetAuthConfig = {
    apiKey: `${randomUUID()}-${randomUUID()}`,
    webhookSecret: randomBytes(32).toString("hex"),
    generatedAt: new Date().toISOString(),
  };
  writeConnectorConfigToDatabase(WIDGET_AUTH_CONFIG_KEY, config);
  return config;
}

/**
 * Verifies an HMAC-SHA256 signature from the WordPress plugin.
 * Uses timingSafeEqual to prevent timing attacks.
 * sigHeader format: "sha256=<hex>"
 */
export function verifyWebhookSignature(
  rawBody: string,
  sigHeader: string,
  secret: string,
): boolean {
  if (!sigHeader.startsWith("sha256=")) return false;
  const expected =
    "sha256=" + createHmac("sha256", secret).update(rawBody).digest("hex");
  const sigBuf = Buffer.from(sigHeader);
  const expectedBuf = Buffer.from(expected);
  if (sigBuf.length !== expectedBuf.length) return false;
  try {
    return timingSafeEqual(sigBuf, expectedBuf);
  } catch {
    return false;
  }
}

/**
 * CORS origin allowlist. Reflects the exact Origin header when it matches a
 * configured WordPress instance siteUrl (case-insensitive, trailing slashes ignored).
 */
export function resolveWordPressWidgetOrigin(originHeader: string | null): string | null {
  if (!originHeader) return null;
  const settings = getWordPressAPISettings();
  const normalize = (v: string) => v.replace(/\/+$/, "").toLowerCase();
  const want = normalize(originHeader);
  for (const instance of settings.instances) {
    if (normalize(instance.siteUrl) === want) return originHeader;
  }
  return null;
}

/**
 * Bearer token validator for the WordPress widget. Compares against the apiKey stored in
 * connector_config (UUID-pair generated by generateWidgetAuthConfig).
 */
export function validateWordPressWidgetToken(token: string): boolean {
  if (!token) return false;
  const config = readWidgetAuthConfig();
  if (!config?.apiKey) return false;
  const a = Buffer.from(token);
  const b = Buffer.from(config.apiKey);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/**
 * CORS headers reflecting the validated origin. Use only after resolveWordPressWidgetOrigin
 * returns non-null.
 */
export function buildWordPressCorsHeaders(allowedOrigin: string): Record<string, string> {
  return {
    "Access-Control-Allow-Origin": allowedOrigin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Credentials": "false",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}
