-- GENERATED by scripts/dump-public-schema.mjs — do not edit by hand.
-- Faithful snapshot of the public schema the RBAC e2e runs against.
-- Regenerate from a working local DB with:
--   node --env-file=.env.local scripts/dump-public-schema.mjs

SET search_path = public, pg_catalog;

DO $$ BEGIN
  CREATE EXTENSION IF NOT EXISTS "btree_gin";
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'skipping extension btree_gin: %', SQLERRM;
END $$;
DO $$ BEGIN
  CREATE EXTENSION IF NOT EXISTS "ltree";
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'skipping extension ltree: %', SQLERRM;
END $$;
DO $$ BEGIN
  CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'skipping extension pg_stat_statements: %', SQLERRM;
END $$;

CREATE SEQUENCE IF NOT EXISTS public."checkpoint_delete_queue_id_seq";

CREATE TABLE IF NOT EXISTS public."account" (
  "id" text NOT NULL,
  "accountId" text NOT NULL,
  "providerId" text NOT NULL,
  "userId" text NOT NULL,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamp with time zone,
  "refreshTokenExpiresAt" timestamp with time zone,
  "scope" text,
  "password" text,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS public."assistant" (
  "assistant_id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "graph_id" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "name" text,
  "description" text,
  "context" jsonb
);
CREATE TABLE IF NOT EXISTS public."assistant_profiles" (
  "id" text NOT NULL,
  "webhookUrl" text,
  "webhookSecret" text,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public."assistant_versions" (
  "assistant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "graph_id" text NOT NULL,
  "config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "name" text,
  "description" text,
  "context" jsonb
);
CREATE TABLE IF NOT EXISTS public."checkpoint_blobs" (
  "thread_id" uuid NOT NULL,
  "channel" text NOT NULL,
  "version" text NOT NULL,
  "type" text NOT NULL,
  "blob" bytea,
  "checkpoint_ns" text DEFAULT ''::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."checkpoint_delete_queue" (
  "id" bigint DEFAULT nextval('checkpoint_delete_queue_id_seq'::regclass) NOT NULL,
  "thread_id" uuid NOT NULL,
  "checkpoint_ns" text DEFAULT ''::text NOT NULL,
  "checkpoint_id" text NOT NULL,
  "enqueued_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public."checkpoint_writes" (
  "thread_id" uuid NOT NULL,
  "checkpoint_id" uuid NOT NULL,
  "task_id" uuid NOT NULL,
  "idx" integer NOT NULL,
  "channel" text NOT NULL,
  "type" text NOT NULL,
  "blob" bytea NOT NULL,
  "checkpoint_ns" text DEFAULT ''::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."checkpoints" (
  "thread_id" uuid NOT NULL,
  "checkpoint_id" uuid NOT NULL,
  "run_id" uuid,
  "parent_checkpoint_id" uuid,
  "checkpoint" jsonb NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "checkpoint_ns" text DEFAULT ''::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."cron" (
  "cron_id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "assistant_id" uuid,
  "thread_id" uuid,
  "user_id" text,
  "payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "schedule" text NOT NULL,
  "next_run_date" timestamp with time zone,
  "end_time" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "on_run_completed" varchar(20) DEFAULT 'delete'::character varying,
  "enabled" boolean DEFAULT true NOT NULL,
  "timezone" text
);
CREATE TABLE IF NOT EXISTS public."invitation" (
  "id" text NOT NULL,
  "organizationId" text NOT NULL,
  "email" text NOT NULL,
  "role" text,
  "status" text NOT NULL,
  "expiresAt" timestamp with time zone NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "inviterId" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."jwks" (
  "id" text NOT NULL,
  "publicKey" text NOT NULL,
  "privateKey" text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "expiresAt" timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public."member" (
  "id" text NOT NULL,
  "organizationId" text NOT NULL,
  "userId" text NOT NULL,
  "role" text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS public."oauthAccessToken" (
  "id" text NOT NULL,
  "token" text NOT NULL,
  "clientId" text NOT NULL,
  "sessionId" text,
  "userId" text,
  "referenceId" text,
  "refreshId" text,
  "expiresAt" timestamp with time zone NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "scopes" jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public."oauthClient" (
  "id" text NOT NULL,
  "clientId" text NOT NULL,
  "clientSecret" text,
  "disabled" boolean,
  "skipConsent" boolean,
  "enableEndSession" boolean,
  "subjectType" text,
  "scopes" jsonb,
  "userId" text,
  "createdAt" timestamp with time zone,
  "updatedAt" timestamp with time zone,
  "name" text,
  "uri" text,
  "icon" text,
  "contacts" jsonb,
  "tos" text,
  "policy" text,
  "softwareId" text,
  "softwareVersion" text,
  "softwareStatement" text,
  "redirectUris" jsonb NOT NULL,
  "postLogoutRedirectUris" jsonb,
  "tokenEndpointAuthMethod" text,
  "grantTypes" jsonb,
  "responseTypes" jsonb,
  "public" boolean,
  "type" text,
  "requirePKCE" boolean,
  "referenceId" text,
  "metadata" jsonb
);
CREATE TABLE IF NOT EXISTS public."oauthConsent" (
  "id" text NOT NULL,
  "clientId" text NOT NULL,
  "userId" text,
  "referenceId" text,
  "scopes" jsonb NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS public."oauthRefreshToken" (
  "id" text NOT NULL,
  "token" text NOT NULL,
  "clientId" text NOT NULL,
  "sessionId" text,
  "userId" text NOT NULL,
  "referenceId" text,
  "expiresAt" timestamp with time zone NOT NULL,
  "createdAt" timestamp with time zone NOT NULL,
  "revoked" timestamp with time zone,
  "authTime" timestamp with time zone,
  "scopes" jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public."organization" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "logo" text,
  "createdAt" timestamp with time zone NOT NULL,
  "metadata" text
);
CREATE TABLE IF NOT EXISTS public."run" (
  "run_id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "thread_id" uuid NOT NULL,
  "assistant_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "kwargs" jsonb NOT NULL,
  "multitask_strategy" text DEFAULT 'reject'::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."schema_migrations" (
  "version" bigint NOT NULL,
  "dirty" boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS public."session" (
  "id" text NOT NULL,
  "expiresAt" timestamp with time zone NOT NULL,
  "token" text NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "userId" text NOT NULL,
  "impersonatedBy" text,
  "activeOrganizationId" text
);
CREATE TABLE IF NOT EXISTS public."store" (
  "prefix" text NOT NULL,
  "key" text NOT NULL,
  "value" jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamp with time zone,
  "ttl_minutes" integer
);
CREATE TABLE IF NOT EXISTS public."team" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "organizationId" text NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
  "slug" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."teamMember" (
  "id" text NOT NULL,
  "teamId" text NOT NULL,
  "userId" text NOT NULL,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public."thread" (
  "thread_id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "status" text DEFAULT 'idle'::text NOT NULL,
  "config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "values" jsonb,
  "interrupts" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "error" bytea,
  "state_updated_at" timestamp with time zone,
  "configured_ttl_strategy" text,
  "configured_ttl_minutes" numeric
);
CREATE TABLE IF NOT EXISTS public."thread_ttl" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "thread_id" uuid NOT NULL,
  "strategy" text DEFAULT 'delete'::text NOT NULL,
  "ttl_minutes" numeric NOT NULL,
  "created_at" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
  "expires_at" timestamp without time zone
);
CREATE TABLE IF NOT EXISTS public."twoFactor" (
  "id" text NOT NULL,
  "secret" text NOT NULL,
  "backupCodes" text NOT NULL,
  "userId" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public."user" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "emailVerified" boolean NOT NULL,
  "image" text,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "username" text,
  "displayUsername" text,
  "role" text,
  "banned" boolean,
  "banReason" text,
  "banExpires" timestamp with time zone,
  "twoFactorEnabled" boolean,
  "userType" text DEFAULT 'human'::text NOT NULL,
  "clientId" text,
  "accent_color" text
);
CREATE TABLE IF NOT EXISTS public."verification" (
  "id" text NOT NULL,
  "identifier" text NOT NULL,
  "value" text NOT NULL,
  "expiresAt" timestamp with time zone NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."account" ADD CONSTRAINT "account_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assistant_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."assistant" ADD CONSTRAINT "assistant_pkey" PRIMARY KEY (assistant_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assistant_profiles_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."assistant_profiles" ADD CONSTRAINT "assistant_profiles_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assistant_versions_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."assistant_versions" ADD CONSTRAINT "assistant_versions_pkey" PRIMARY KEY (assistant_id, version);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkpoint_blobs_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."checkpoint_blobs" ADD CONSTRAINT "checkpoint_blobs_pkey" PRIMARY KEY (thread_id, checkpoint_ns, channel, version);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkpoint_delete_queue_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."checkpoint_delete_queue" ADD CONSTRAINT "checkpoint_delete_queue_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkpoint_writes_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."checkpoint_writes" ADD CONSTRAINT "checkpoint_writes_pkey" PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkpoints_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."checkpoints" ADD CONSTRAINT "checkpoints_pkey" PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cron_on_run_completed_check' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."cron" ADD CONSTRAINT "cron_on_run_completed_check" CHECK (((on_run_completed)::text = ANY ((ARRAY['delete'::character varying, 'keep'::character varying])::text[])));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cron_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."cron" ADD CONSTRAINT "cron_pkey" PRIMARY KEY (cron_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'invitation_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."invitation" ADD CONSTRAINT "invitation_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'jwks_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."jwks" ADD CONSTRAINT "jwks_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'member_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."member" ADD CONSTRAINT "member_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_token_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_token_key" UNIQUE (token);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthClient_clientId_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthClient" ADD CONSTRAINT "oauthClient_clientId_key" UNIQUE ("clientId");
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthClient_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthClient" ADD CONSTRAINT "oauthClient_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthConsent_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthConsent" ADD CONSTRAINT "oauthConsent_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthRefreshToken_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'organization_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."organization" ADD CONSTRAINT "organization_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'organization_slug_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."organization" ADD CONSTRAINT "organization_slug_key" UNIQUE (slug);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'run_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."run" ADD CONSTRAINT "run_pkey" PRIMARY KEY (run_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'schema_migrations_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."schema_migrations" ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY (version);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'session_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."session" ADD CONSTRAINT "session_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'session_token_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."session" ADD CONSTRAINT "session_token_key" UNIQUE (token);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'store_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."store" ADD CONSTRAINT "store_pkey" PRIMARY KEY (prefix, key);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."team" ADD CONSTRAINT "team_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_slug_format' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."team" ADD CONSTRAINT "team_slug_format" CHECK (((slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'::text) AND (slug !~~ '~%'::text)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teamMember_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."teamMember" ADD CONSTRAINT "teamMember_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'thread_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."thread" ADD CONSTRAINT "thread_pkey" PRIMARY KEY (thread_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'thread_ttl_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."thread_ttl" ADD CONSTRAINT "thread_ttl_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'thread_ttl_ttl_minutes_check' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."thread_ttl" ADD CONSTRAINT "thread_ttl_ttl_minutes_check" CHECK ((ttl_minutes >= (0)::numeric));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'twoFactor_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."twoFactor" ADD CONSTRAINT "twoFactor_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_accent_color_check' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."user" ADD CONSTRAINT "user_accent_color_check" CHECK (((accent_color IS NULL) OR (accent_color = ANY (ARRAY['red'::text, 'burgundy'::text, 'indigo'::text, 'green'::text, 'mustard'::text, 'slate'::text]))));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_email_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."user" ADD CONSTRAINT "user_email_key" UNIQUE (email);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."user" ADD CONSTRAINT "user_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_username_key' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."user" ADD CONSTRAINT "user_username_key" UNIQUE (username);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'verification_pkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."verification" ADD CONSTRAINT "verification_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assistant_versions_assistant_id_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."assistant_versions" ADD CONSTRAINT "assistant_versions_assistant_id_fkey" FOREIGN KEY (assistant_id) REFERENCES assistant(assistant_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cron_assistant_id_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."cron" ADD CONSTRAINT "cron_assistant_id_fkey" FOREIGN KEY (assistant_id) REFERENCES assistant(assistant_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cron_thread_id_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."cron" ADD CONSTRAINT "cron_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES thread(thread_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'invitation_inviterId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."invitation" ADD CONSTRAINT "invitation_inviterId_fkey" FOREIGN KEY ("inviterId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'invitation_organizationId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."invitation" ADD CONSTRAINT "invitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'member_organizationId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."member" ADD CONSTRAINT "member_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'member_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."member" ADD CONSTRAINT "member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_clientId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "oauthClient"("clientId") ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_refreshId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_refreshId_fkey" FOREIGN KEY ("refreshId") REFERENCES "oauthRefreshToken"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_sessionId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES session(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthAccessToken_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthClient_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthClient" ADD CONSTRAINT "oauthClient_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthConsent_clientId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthConsent" ADD CONSTRAINT "oauthConsent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "oauthClient"("clientId") ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthConsent_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthConsent" ADD CONSTRAINT "oauthConsent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthRefreshToken_clientId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "oauthClient"("clientId") ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthRefreshToken_sessionId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES session(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oauthRefreshToken_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'session_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_organizationId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."team" ADD CONSTRAINT "team_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teamMember_teamId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."teamMember" ADD CONSTRAINT "teamMember_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES team(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teamMember_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."teamMember" ADD CONSTRAINT "teamMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'thread_ttl_thread_id_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."thread_ttl" ADD CONSTRAINT "thread_ttl_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES thread(thread_id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'twoFactor_userId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE public."twoFactor" ADD CONSTRAINT "twoFactor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "account_userId_idx" ON public.account USING btree ("userId");
CREATE INDEX IF NOT EXISTS assistant_created_at_idx ON public.assistant USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS assistant_graph_id_idx ON public.assistant USING btree (graph_id, created_at DESC);
CREATE INDEX IF NOT EXISTS assistant_metadata_idx ON public.assistant USING gin (metadata jsonb_path_ops);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cdq_dedup ON public.checkpoint_delete_queue USING btree (thread_id, checkpoint_ns, checkpoint_id);
CREATE INDEX IF NOT EXISTS checkpoints_checkpoint_id_idx ON public.checkpoints USING btree (thread_id, checkpoint_id DESC);
CREATE INDEX IF NOT EXISTS checkpoints_run_id_idx ON public.checkpoints USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_cron_next_run_enabled ON public.cron USING btree (next_run_date) WHERE (enabled = true);
CREATE INDEX IF NOT EXISTS invitation_email_idx ON public.invitation USING btree (email);
CREATE INDEX IF NOT EXISTS "invitation_organizationId_idx" ON public.invitation USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS "member_organizationId_idx" ON public.member USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS "member_userId_idx" ON public.member USING btree ("userId");
CREATE UNIQUE INDEX IF NOT EXISTS member_org_user_uniq ON public."member" ("organizationId", "userId");
CREATE UNIQUE INDEX IF NOT EXISTS organization_slug_uidx ON public.organization USING btree (slug);
CREATE INDEX IF NOT EXISTS idx_run_thread_running ON public.run USING btree (thread_id) WHERE (status = 'running'::text);
CREATE INDEX IF NOT EXISTS run_pending_by_thread_time_cover ON public.run USING btree (thread_id, created_at, run_id) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS run_thread_id_idx ON public.run USING btree (thread_id);
CREATE INDEX IF NOT EXISTS "session_userId_idx" ON public.session USING btree ("userId");
CREATE INDEX IF NOT EXISTS idx_store_expires_at ON public.store USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS store_prefix_idx ON public.store USING btree (prefix text_pattern_ops);
CREATE INDEX IF NOT EXISTS team_org_idx ON public.team USING btree ("organizationId");
CREATE UNIQUE INDEX IF NOT EXISTS team_slug_uniq_in_org ON public.team USING btree ("organizationId", slug);
CREATE INDEX IF NOT EXISTS team_member_team_idx ON public."teamMember" USING btree ("teamId");
CREATE INDEX IF NOT EXISTS team_member_user_idx ON public."teamMember" USING btree ("userId");
CREATE INDEX IF NOT EXISTS thread_created_at_idx ON public.thread USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS thread_metadata_idx ON public.thread USING gin (metadata jsonb_path_ops);
CREATE INDEX IF NOT EXISTS thread_owner_updated_idx ON public.thread USING btree (((metadata ->> 'owner'::text)), updated_at DESC, thread_id DESC) WHERE (metadata ? 'owner'::text);
CREATE INDEX IF NOT EXISTS thread_status_idx ON public.thread USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS thread_values_idx ON public.thread USING gin ("values" jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_thread_ttl_expires_at ON public.thread_ttl USING btree (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_thread_ttl_thread_strategy ON public.thread_ttl USING btree (thread_id, strategy);
CREATE INDEX IF NOT EXISTS user_client_id_idx ON public."user" USING btree ("clientId") WHERE ("clientId" IS NOT NULL);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON public.verification USING btree (identifier);

