// Deeplink: Better Auth account view surfaced during MCP OAuth handshake; URL generated by the library, not linked from app chrome.
import type { Metadata } from "next";
import { accountViewPaths } from "@daveyplate/better-auth-ui/server";
import { mcpServerMount } from "@/lib/mcp-server";

export const metadata: Metadata = { title: "Account" };

export const dynamicParams = false;

export async function generateStaticParams() {
  return Object.values(accountViewPaths).map((path) => ({ path }));
}

const { AccountPage } = mcpServerMount;

export default function McpAccountRoutePage(
  props: Parameters<typeof AccountPage>[0],
) {
  return <AccountPage {...props} />;
}
