// gen-wayflow-env.mjs — narrow WayFlow container env generator.
//
// WHY THIS EXISTS
// The wayflow docker service authenticates its callback to the host
// /api/llm-bridge with X-Cinatra-Bridge-Token. The compose file MUST NOT read
// that secret via `environment: CINATRA_BRIDGE_TOKEN: "${CINATRA_BRIDGE_TOKEN}"`
// because that interpolation resolves the *shell* env (empty on a bare
// `docker compose up`) AND an empty `environment:` value OVERRIDES an `env_file`
// value on the same key — so the bridge silently 403s and the widget
// content-edit returns "(no response)". The fix sources the three host-secret
// keys from a NARROW generated file (docker/wayflow/.wayflow.env) referenced via
// `env_file`, with NO overlapping `environment:` mapping.
//
// These tests pin:
//  1. buildWayflowEnv extracts EXACTLY the wayflow keys, defaults
//     WAYFLOW_BASE_URL, and reports missing required secrets.
//  2. serializeDotenv emits bare KEY=VALUE the compose env_file parser accepts.
//  3. parseDotenv strips quotes (parity with check-services.mjs).
//  4. THE COMPOSE NO-OVERLAP INVARIANT: the wayflow service's `environment:`
//     block shares NO key with the env_file's keys (else the empty-override
//     trap recurs), AND references docker/wayflow/.wayflow.env via env_file.

import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseDotenv,
  buildWayflowEnv,
  serializeDotenv,
} from "../gen-wayflow-env.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");

// The three keys the wayflow container needs from host secrets. Kept in sync
// with WAYFLOW_KEYS in the generator (asserted indirectly via buildWayflowEnv).
const WAYFLOW_KEYS = ["CINATRA_BRIDGE_TOKEN", "OPENAI_API_KEY", "WAYFLOW_BASE_URL"];

describe("gen-wayflow-env — parseDotenv", () => {
  it("parses KEY=VALUE and strips surrounding quotes", () => {
    const env = parseDotenv('A=1\nB="two"\nC=\'three\'\n# comment\nBAD LINE\n');
    expect(env).toEqual({ A: "1", B: "two", C: "three" });
  });
});

describe("gen-wayflow-env — buildWayflowEnv", () => {
  it("extracts exactly the wayflow keys (ignores everything else)", () => {
    const { env } = buildWayflowEnv({
      CINATRA_BRIDGE_TOKEN: "tok-123",
      OPENAI_API_KEY: "sk-abc",
      WAYFLOW_BASE_URL: "http://localhost:3010",
      // Sensitive keys that must NEVER reach the wayflow container:
      BETTER_AUTH_SECRET: "nope",
      CINATRA_ENCRYPTION_KEY: "nope",
      NANGO_SECRET_KEY: "nope",
      PORT: "3000", // app port — must not clobber the container's 3010
    });
    expect(Object.keys(env).sort()).toEqual([...WAYFLOW_KEYS].sort());
    expect(env.CINATRA_BRIDGE_TOKEN).toBe("tok-123");
    expect(env.OPENAI_API_KEY).toBe("sk-abc");
    expect(env).not.toHaveProperty("BETTER_AUTH_SECRET");
    expect(env).not.toHaveProperty("PORT");
  });

  it("defaults WAYFLOW_BASE_URL when absent but never the secrets", () => {
    const { env, missing } = buildWayflowEnv({ CINATRA_BRIDGE_TOKEN: "t" });
    expect(env.WAYFLOW_BASE_URL).toBe("http://localhost:3010");
    expect(env.CINATRA_BRIDGE_TOKEN).toBe("t");
    // OPENAI_API_KEY absent → reported missing, never defaulted.
    expect(missing).toContain("OPENAI_API_KEY");
    expect(env).not.toHaveProperty("OPENAI_API_KEY");
  });

  it("treats a whitespace-only bridge token as MISSING", () => {
    const { env, missing } = buildWayflowEnv({
      CINATRA_BRIDGE_TOKEN: "   ",
      OPENAI_API_KEY: "sk",
    });
    expect(missing).toContain("CINATRA_BRIDGE_TOKEN");
    expect(env).not.toHaveProperty("CINATRA_BRIDGE_TOKEN");
  });

  it("trims surrounding whitespace from kept values", () => {
    const { env } = buildWayflowEnv({
      CINATRA_BRIDGE_TOKEN: "  tok  ",
      OPENAI_API_KEY: "sk",
    });
    expect(env.CINATRA_BRIDGE_TOKEN).toBe("tok");
  });
});

describe("gen-wayflow-env — serializeDotenv", () => {
  it("emits bare KEY=VALUE lines (no quoting) the env_file parser accepts", () => {
    const text = serializeDotenv({ CINATRA_BRIDGE_TOKEN: "tok", OPENAI_API_KEY: "sk" });
    expect(text).toMatch(/^CINATRA_BRIDGE_TOKEN=tok$/m);
    expect(text).toMatch(/^OPENAI_API_KEY=sk$/m);
    // No surrounding quotes on values (compose would embed them literally).
    expect(text).not.toMatch(/=".*"/);
    // Carries a DO-NOT-EDIT header.
    expect(text).toMatch(/GENERATED by scripts\/gen-wayflow-env\.mjs/);
  });
});

describe("docker-compose wayflow service — no env_file/environment overlap", () => {
  const composePath = path.join(REPO_ROOT, "docker-compose.yml");
  const yaml = fs.existsSync(composePath)
    ? fs.readFileSync(composePath, "utf8")
    : "";

  // Extract the `wayflow:` service block (from `  wayflow:` up to the next
  // top-level 2-space-indented service key). No YAML dep (matches the existing
  // a2a-peer-compose.test.ts convention).
  function wayflowBlock() {
    const lines = yaml.split("\n");
    const start = lines.findIndex((l) => /^  wayflow:\s*$/.test(l));
    expect(start).toBeGreaterThanOrEqual(0);
    let end = lines.length;
    for (let i = start + 1; i < lines.length; i++) {
      if (/^  [A-Za-z0-9_-]+:\s*$/.test(lines[i])) {
        end = i;
        break;
      }
    }
    return lines.slice(start, end);
  }

  it("references docker/wayflow/.wayflow.env via env_file (required:false)", () => {
    const block = wayflowBlock().join("\n");
    expect(block).toMatch(/env_file:/);
    expect(block).toMatch(/path:\s*\.\/docker\/wayflow\/\.wayflow\.env/);
    expect(block).toMatch(/required:\s*false/);
  });

  it("has NO environment: key that overlaps the env_file's wayflow keys", () => {
    const block = wayflowBlock();
    // Collect keys under the `environment:` mapping (4-space-indented `KEY:`
    // entries directly under the 4-space `environment:` line).
    const envStart = block.findIndex((l) => /^    environment:\s*$/.test(l));
    const envKeys = [];
    if (envStart >= 0) {
      for (let i = envStart + 1; i < block.length; i++) {
        const line = block[i];
        if (/^    [A-Za-z0-9_-]+:/.test(line) && !/^      /.test(line)) break;
        const m = line.match(/^      ([A-Z0-9_]+):/);
        if (m) envKeys.push(m[1]);
      }
    }
    // The trap: any of the three host-secret keys appearing inline would
    // interpolate to "" (shell unset) and OVERRIDE the env_file value.
    for (const k of WAYFLOW_KEYS) {
      expect(envKeys).not.toContain(k);
    }
    // And the static keys we DO keep inline must still be present (so PORT is
    // pinned to 3010 here, not inherited from .env.local's app PORT).
    expect(envKeys).toContain("PORT");
    expect(envKeys).toContain("CINATRA_AGENTS_DIR");
    expect(envKeys).toContain("CINATRA_BASE_URL");
  });
});
