// Deeplink: Better Auth permission view paths; URLs are generated by the library and reached via OrganizationView / AccountView links.
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import PermissionsOrganizationPage from "@cinatra-ai/permissions/organization-page";
import { organizationViewPaths } from "@daveyplate/better-auth-ui/server";

export const metadata: Metadata = { title: "Organization" };

export const dynamicParams = false;

export async function generateStaticParams() {
  return Object.values(organizationViewPaths)
    .filter((path) => path !== organizationViewPaths.SETTINGS && path !== organizationViewPaths.MEMBERS)
    .map((path) => ({ path }));
}

export default async function PermissionsOrganizationRoutePage(
  props: Parameters<typeof PermissionsOrganizationPage>[0],
) {
  const { path } = await props.params;
  if (path === organizationViewPaths.SETTINGS || path === organizationViewPaths.MEMBERS) notFound();
  return <PermissionsOrganizationPage {...props} />;
}
